functions {
  //Function that describes changes in the source chimerism
  real chi_source(real time) {
    // real chi_est = 0.93;
    // real nu = 0.16;
    real chi_est = 0.85;
    real nu = 0.1;
    real t0 = 10; // t0 is the minimun days post bmt 
    real chi_s;
    
    if ((time - t0) < 0) {
      chi_s = 0; // conditioning the function to adapt to the timepoints before BMT
    } else {
      chi_s = chi_est * (1 - exp(-nu * (time - t0)));
  
    }
    
    return chi_s;
  }
  //Function explainig division
real rho_td(real time, real rho, real r_d )  
{ 
    real rho_td = rho / (1 + (time -40)/r_d); 
    return rho_td;
  }

  //Function that describes changes in the Ki67+ donor cells 
  real eps_donor(real time) {

    real m = -3.79e-5;
    real c = 0.99;
    real t0 = 40; // t0 is the minimun days post bmt 
    real e_d;
    
    if ((time - t0) < 0) {
      e_d = 0; // conditioning the function to adapt to the timepoints before BMT
    } else {
      e_d = m*(time-t0) + c;
  
    }

    return e_d;
  }

    //Function that describes changes in the Ki67+ host cells 
  real eps_host(real time) {

    real m = -1.7e-4;
    real c = 0.98;
    real t0 = 40; // t0 is the minimun days post bmt 
    real e_h;
    
    if ((time - t0) < 0) {
      e_h = 0; // conditioning the function to adapt to the timepoints before BMT
    } else {
      e_h = m*(time-t0) + c;
  
    }

    return e_h;
  }

  //Function that contain the ODE equations to be used in the ODE solver
  vector Ode_sys(real time, //time
                 vector X, //state,
                 array[] real parms //parameters
                 ) {
    // parameters
    real phi = parms[1]; //loss rate
    real rho = parms[2]; //division rate
    real r_d = parms[3]; //rate of change of influx rate
    real ageATBMT = parms[4]; //age at BMT
    
    // fixed parameters
    real P = 1298783; //mean of the precursor counts 
    real beta= 3.5;

    real M_stable = X[1] + X[2] + X[3] + X[4]; // total counts at steady state
    real delta = ((phi * P)/M_stable) + rho_td(time, rho, r_d); //influx rate calculated from the loss and division rate
    
    // the system of ODEs
    vector[4] dXdt;
    //donor Ki67+ cells
    dXdt[1] = phi * eps_donor(time) * chi_source(time - ageATBMT) * P
              + rho_td(time, rho, r_d) * (X[1] + 2 * X[2]) - ((1 / beta) + delta) * X[1];
    //donor Ki67- cells
    dXdt[2] = phi * (1 - eps_donor(time)) * chi_source(time - ageATBMT) * P
                  + (1 / beta) * X[1] - (rho_td(time, rho, r_d) + delta) * X[2];
        //host Ki67+ cells
    dXdt[3] = phi * eps_host(time) * (1 - chi_source(time - ageATBMT)) * P
              + rho_td(time, rho, r_d) * (X[3] + 2 * X[4]) - ((1 / beta) + delta) * X[3];
    //host Ki67- cells
    dXdt[4] = phi * (1 - eps_host(time)) * (1 - chi_source(time - ageATBMT))* P
             + (1 / beta) * X[3] - (rho_td(time, rho, r_d) + delta) * X[4];
    return dXdt;
  }
  
   //we define a solver to generate initial conditions at each age at BMT, using the earliest age at BMT as t_0
  vector initial_cond_generator(vector initial_cond, real solve_time,
                                 array[] real parms) {
    array[1] vector[4] solution;
    array[4] real par_tb; // parameters for the intial_cond_generator
    par_tb[1 : 3] = parms[1 : 3];
    par_tb[4] = 40.0; // use the earliest age at BMT 
    solution = ode_rk45(Ode_sys, initial_cond, 40, rep_array(solve_time,1), par_tb); // ode_rk5 is the ode solver which give an array vector of 4
    return to_vector(solution[1]);
  }

// we define a solver to generate the predicted values at each time point using initial conditions generated by the initial_cond_generator
vector prediction_generator(vector initial_cond, real solve_time,
real ageatBMT, array[] real parms) {
vector[4] initial_tbmt; // solution of the initial_cond_generator
vector[4] y0; // initial conditions for the solve time evaluation
array[1] vector[4] solution;

array[4] real par_tb; // parameters for the intial_cond_generator
par_tb[1 : 3] = parms[1 : 3];
par_tb[4] = ageatBMT;

initial_tbmt = initial_cond_generator(initial_cond, ageatBMT, par_tb);
// For every time point(each mouse), we set the first two initial conditions (for donor compartment) to be zero because age at bmt(t0), donor counts are zero.
y0[1] = 0;
y0[2] = 0;
y0[3] = initial_tbmt[1] + initial_tbmt[3];
y0[4] = initial_tbmt[2] + initial_tbmt[4];

solution = ode_rk45(Ode_sys, y0, ageatBMT, rep_array(solve_time, 1), par_tb);
return to_vector(solution[1]);
}

// define a function to solve the ODEs for each solve time using corresponding age at BMT
vector ode_pred(vector initial_cond, array[] real pred_time, real ageatBMT,
array[] real parms) {
int num_time = size(pred_time);

vector[4 * num_time] solution;

vector[4] initial_tbmt; // solution of the initial_cond_generator
vector[4] y0; // initial conditions for the solve time evaluation
array[4] real par_tb; // parameters for the intial_cond_generator
vector[4] initial_tbmt_1d;

par_tb[1 : 3] = parms[1 : 3];
par_tb[4] = ageatBMT;

initial_tbmt = initial_cond_generator(initial_cond, ageatBMT, par_tb);
//initial_tbmt = initial_cond_generator(initial_cond, pred_time[1], par_tb);
// For every time point(each mouse), we set the first two initial conditions (for donor compartment) to be zero because age at bmt(t0), donor counts are zero.
y0[1] = 0;
y0[2] = 0;
y0[3] = initial_tbmt[1] + initial_tbmt[3];
y0[4] = initial_tbmt[2] + initial_tbmt[4];

for (i in 1 : num_time) {
//solution[4 * i - 3 : 4 * i] = initial_cond_generator(y0, pred_time[i],
                            // par_tb);
solution[4 * i - 3 : 4 * i] = ode_rk45(Ode_sys, y0, ageatBMT, rep_array(pred_time[i], 1),
                             par_tb)[1];                                                     
}

return solution;
}

// define a function to parallelize the ode_solver
vector map_rect_helper_func(vector eta, vector theta, array[] real x_r,
array[] int x_i) {
vector[4] initial_cond = eta[1 : 4];
array[3] real parms = to_array_1d(eta[5 : 7]);
real solve_time = x_r[1];
real ageatBMT = x_r[2];

vector[4] solution = prediction_generator(initial_cond, solve_time,
                ageatBMT, parms);
return solution;
}

array[] vector ode_solver_parallel(vector initial_cond,
       data array[,] real solve_time_ageatBMT,
       array[] real parms) {
int num_time = size(solve_time_ageatBMT[ : , 1]);
vector[7] eta = append_row(initial_cond, to_vector(parms));
array[num_time] vector[0] theta;

array[num_time, 0] int x_i;

vector[4 * num_time] solution_concat = map_rect(map_rect_helper_func,
                      eta, theta,
                      solve_time_ageatBMT, x_i);

array[num_time] vector[4] solution;

for (i in 1 : num_time) {
solution[i,  : ] = solution_concat[(4 * (i - 1) + 1) : (4 * i)];
}

return solution;
}

  // functions for data transformations
  array[] real logit_boundary_array(array[] real x) {
    int ndims = size(x);
    array[ndims] real answer;
    real b = 1.2;
    for (i in 1 : ndims) {
      answer[i] = log(x[i] / (b - x[i]));
    }
    return answer;
  }

  real logit_boundary(real x) {
    real answer;
    real b = 1.2;
    answer = log(x / (b - x));
    return answer;
  }

  array[] real expit_boundary_array(array[] real x){
    int ndims = size(x);
    array[ndims] real answer;
    real b = 1.2;

    for (i in 1: ndims){
      answer[i] =  (b * exp(x[i])) /( 1+ exp(x[i]));
    }

    return answer;
  }

  real expit_boundary(real x){
    real answer;
    real b = 1.2;

    answer =  (b * exp(x)) /( 1+ exp(x));

    return answer;
  }
}


data {
  int<lower=1> numobs; // number of observations in the dataset
  int<lower=1> numsolve; // number of unique time points for ODE solver
  int<lower=1> numpred1; // number of predicted time points 
  int<lower=1> numpred2; // number of predicted time points
  array[numobs] real data_time; // observed Nfd dataset
  array[numobs] int time_index_map; // time map for dataset
  array[numsolve] real solve_time; // solve time for ode solver for Ki67 dataset
  array[numsolve] real solve_ageatBMT;
  array[numobs] real dayspbmt; // observed data set 
  array[numobs] real ageatbmt;
  array[numobs] real totalMZ;
  array[numobs] real Nfd;
  array[numobs] real ki_donor;
  array[numobs] real ki_host;
  array[numpred1] real time_pred1_solve; // predicted time points
  array[numpred2] real time_pred2_solve;
  real time_pred1_bmt;
  real time_pred2_bmt;
}

transformed data {
  array[numobs] real y1;
  array[numobs] real y2;
  array[numobs] real y3;
  array[numobs] real y4;

  array[numsolve, 2] real solve_time_ageatBMT;
  solve_time_ageatBMT[ : , 1] = solve_time;
  solve_time_ageatBMT[ : , 2] = solve_ageatBMT;

  y1 = log(totalMZ); // transforming cell counts of donor compartments to feed in to ODEs
  y2 = Nfd; // transfored donor fractions normalised to source chimerism to feed in to ODEs
  y3 = ki_donor; // transforming counts of ki67 positive cells in the donor compartments to feed in to ODEs
  y4 = ki_host; // transforming counts of ki67 positive cells in the host compartments to feed in to ODEs
}

parameters {
  real<lower=0, upper=15> y0_Log;
  real<lower=0, upper=1> kappa_0;
  vector<lower=0>[4] sigma; // measurement error
  real<lower=0> phi; //influx rate
  real<lower=0> rho; //division rate
  real<lower=0> r_d;

}

transformed parameters {
  // solution of the system of ODEs for the predictor values
  array[numsolve] vector[4] k_hat; // declaring the array for ODE solution
  array[numobs] real totalMz_mean; // predictions for dataset1 based on ODE solution
  array[numobs] real Nfd_mean; // predictions for dataset2 based on ODE solution
  array[numobs] real Kid_mean; // predictions for dataset3 based on ODE solution
  array[numobs] real Kih_mean; // predictions for dataset4 based on ODE solution

  array[numsolve] real MZ_counts_mean;
  array[numsolve] real donor_fractions_mean;
  array[numsolve] real host_ki_mean;
  array[numsolve] real donor_ki_mean;

  array[3] real parms; // declaring the array for parameters
  vector[4] initial_cond; // declaring the array for state variables

  real y0 = exp(y0_Log); // transformed parameters for better/faster sampling
  // real rho = exp(rho_Log); // transformed parameters for better/faster sampling
  // real delta = exp(delta_Log); // transformed parameters for better/faster sampling

  // initial conditions and parameters
  // kapp0 = ki67 proportions within host at t0 estimated from the model fit
  // at t0 donor counts i.e Nd_0 = 0 --> Nh_0 = N0
  // also kappa_host_0 = kapp0
  initial_cond[1] = 0.0;
  initial_cond[2] = 0.0;
  initial_cond[3] = y0 * kappa_0;
  initial_cond[4] = y0 * (1 - kappa_0);

  // parameters for the ODEs
  parms[1] = phi;
  parms[2] = rho;
  parms[3] = r_d;

  // solution of the system of ODEs for the predictor values
  //k_hat = ode_solver(initial_cond, solve_time, solve_ageatBMT, parms);
  k_hat = ode_solver_parallel(initial_cond, solve_time_ageatBMT, parms);

  for (i in 1 : numsolve) {
    // total counts
    MZ_counts_mean[i] = k_hat[i, 1] + k_hat[i, 2] + k_hat[i, 3] + k_hat[i, 4];

    // donor fractions normalised with chimerism in the source
    donor_fractions_mean[i] = (k_hat[i, 1] + k_hat[i, 2]) / MZ_counts_mean[i];

    // fractions of ki67 positive cells in the donor compartment
    donor_ki_mean[i] = k_hat[i, 1] / (k_hat[i, 1] + k_hat[i, 2]);

    // fractions of ki67 positive cells in the host compartment
    host_ki_mean[i] = k_hat[i, 3] / (k_hat[i, 3] + k_hat[i, 4]);
  }

  for (i in 1 : numobs) {
    // total counts
    totalMz_mean[i] = MZ_counts_mean[time_index_map[i]];

    // donor fractions normalised with chimerism in the source
    Nfd_mean[i] = donor_fractions_mean[time_index_map[i]] / chi_source(dayspbmt[i]);
    //Nfd_mean[i] = donor_fractions_mean[time_index_map[i]] / 0.79;
 
    // fractions of ki67 positive cells in the donor compartment
    Kid_mean[i] = donor_ki_mean[time_index_map[i]];

    // fractions of ki67 positive cells in the host compartment
    Kih_mean[i] = host_ki_mean[time_index_map[i]];
  }
}

model {
 // prior distributions for the parameters
  r_d ~ normal(60, 20);
  y0_Log ~ normal(14, 2);
  kappa_0 ~ normal(0.1, 0.15);
  rho ~ normal(0.1, 0.2);
  phi ~ normal(0.01, 0.25);

  // prior distributions for the measurement error
  sigma[1] ~ normal(0.6, 0.25);
  sigma[2] ~ normal(3, 0.5);
  sigma[3] ~ normal(0.3, 0.2);
  sigma[4] ~ normal(0.9, 1);

  // likelihood of the observed data given the model prediction 
  y1 ~ normal(log(totalMz_mean), sigma[1]);
  y2 ~ normal(Nfd_mean, sigma[2]);
  y3 ~ normal(Kid_mean, sigma[3]);
  y4 ~ normal(Kih_mean, sigma[4]);
}

generated quantities {

  vector[4 * numpred1] k_hat_pred1 = ode_pred(initial_cond, time_pred1_solve, time_pred1_bmt, parms);
  vector[4 * numpred2] k_hat_pred2 = ode_pred(initial_cond, time_pred2_solve, time_pred2_bmt, parms);


  // Predictions for the predicted time points
  array[numpred1] real MZ_counts_pred1;
  array[numpred1] real Nfd_pred1;
  array[numpred1] real host_ki_pred1;
  array[numpred1] real donor_ki_pred1;

  array[numpred2] real MZ_counts_pred2;
  array[numpred2] real Nfd_pred2;
  array[numpred2] real host_ki_pred2;
  array[numpred2] real donor_ki_pred2;

  // Errors for the predicted time points
  array[numpred1] real MZ_counts_pred1_err;
  array[numpred1] real Nfd_pred1_err;
  array[numpred1] real host_ki_pred1_err;
  array[numpred1] real donor_ki_pred1_err;

  array[numpred2] real MZ_counts_pred2_err;
  array[numpred2] real Nfd_pred2_err;
  array[numpred2] real host_ki_pred2_err;
  array[numpred2] real donor_ki_pred2_err;

  //Replicated data for posterior predictive checks
  array[numobs] real y1_rep;
  array[numobs] real y2_rep;
  array[numobs] real y3_rep;
  array[numobs] real y4_rep;

  y1_rep = normal_rng(log(totalMz_mean), sigma[1]);
  y2_rep = normal_rng(Nfd_mean, sigma[2]);
  y3_rep = normal_rng(Kid_mean, sigma[3]);
  y4_rep = normal_rng(Kih_mean, sigma[4]);
  
  for (i in 1 : numpred1) {
    MZ_counts_pred1[i] = k_hat_pred1[4 * i - 3] + k_hat_pred1[4 * i - 2] + k_hat_pred1[4 * i - 1] + k_hat_pred1[4 * i];
    MZ_counts_pred1_err[i] = exp(normal_rng(log(MZ_counts_pred1[i]), sigma[1]));

    Nfd_pred1[i] = (k_hat_pred1[4 * i - 3] + k_hat_pred1[4 * i - 2]) / (MZ_counts_pred1[i] * chi_source(time_pred1_solve[i] - time_pred1_bmt));
    Nfd_pred1_err[i] = normal_rng(Nfd_pred1[i], sigma[2]);

    donor_ki_pred1[i] = k_hat_pred1[4 * i - 3] / (k_hat_pred1[4 * i - 3] + k_hat_pred1[4 * i - 2]);
    donor_ki_pred1_err[i] = normal_rng(donor_ki_pred1[i], sigma[3]);

    host_ki_pred1[i] = k_hat_pred1[4 * i - 1] / (k_hat_pred1[4 * i - 1] + k_hat_pred1[4 * i]);
    host_ki_pred1_err[i] = normal_rng(host_ki_pred1[i], sigma[4]);
  }

  for (i in 1 : numpred2) {
    MZ_counts_pred2[i] = k_hat_pred2[4 * i - 3] + k_hat_pred2[4 * i - 2] + k_hat_pred2[4 * i - 1] + k_hat_pred2[4 * i];
    MZ_counts_pred2_err[i] = exp(normal_rng(log(MZ_counts_pred2[i]), sigma[1]));

    Nfd_pred2[i] = (k_hat_pred2[4 * i - 3] + k_hat_pred2[4 * i - 2]) / (MZ_counts_pred2[i] * chi_source(time_pred2_solve[i] - time_pred2_bmt));
    Nfd_pred2_err[i] = normal_rng(Nfd_pred2[i], sigma[2]);

    donor_ki_pred2[i] = k_hat_pred2[4 * i - 3] / (k_hat_pred2[4 * i - 3] + k_hat_pred2[4 * i - 2]);
    donor_ki_pred2_err[i] = normal_rng(donor_ki_pred2[i], sigma[3]);
    
    host_ki_pred2[i] = k_hat_pred2[4 * i - 1] / (k_hat_pred2[4 * i - 1] + k_hat_pred2[4 * i]);
    host_ki_pred2_err[i] = normal_rng(host_ki_pred2[i], sigma[4]);
  }

//Division rate 
    array[numpred1] real rho_rate;
    for (i in 1:numpred1) {
          rho_rate[i] = rho_td(time_pred1_solve[i], rho, r_d );
   }
   
  // log likelihood of the observed data given the model prediction
  vector[numobs] log_lik_Mz;
  vector[numobs] log_lik_Nfd;
  vector[numobs] log_lik_Kid;
  vector[numobs] log_lik_Kih;
  vector[numobs] log_lik_total;
 
  // calculating the log predictive accuracy for each point
  for (i in 1 : numobs) {
    log_lik_Mz[i] = normal_lpdf(y1[i] | log(totalMz_mean[i]), sigma[1]);
    log_lik_Nfd[i] = normal_lpdf(y2[i] | Nfd_mean[i], sigma[2]);
    log_lik_Kid[i] = normal_lpdf(y3[i] | Kid_mean[i], sigma[3]);
    log_lik_Kih[i] = normal_lpdf(y4[i] | Kih_mean[i], sigma[4]);
    log_lik_total[i] = log_lik_Mz[i] + log_lik_Nfd[i] + log_lik_Kid[i] + log_lik_Kih[i];
  }

// Calculate residuals for the observed data
  array[numobs] real residuals_Mz;
  array[numobs] real residuals_Nfd;
  array[numobs] real residuals_Kid;
  array[numobs] real residuals_Kih;

  for (i in 1 : numobs) {
    residuals_Mz[i] = y1[i] - log(totalMz_mean[i]);
    residuals_Nfd[i] = y2[i] - Nfd_mean[i];
    residuals_Kid[i] = y3[i] - Kid_mean[i];
    residuals_Kih[i] = y4[i] - Kih_mean[i];
  }
}